/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in installed projects. It is checked in here
// so the TypeScript app is complete before dependencies are installed.
